### ISSUE TITLE
Support for Constants

### ISSUE THREAD

**Issue by mannprerak2** [terrier989/ffi_tool#17]
Support for constants should be added.
(By constants I mean those defined using #define symbol in c/c++)

The input could be:
```dart
Constants(
className: 'Constants',
dartdoc: 'Contains some constants'
constants: [
Const('name',value),
Const('anotherName',value, dartdoc: "Just a constant"),
])
```
The output is
```dart
class Cosntants{
static const name = value;
/// Just a constant
static const anotherName = value;
}
```

I know this may not seem essential and a user can write these on their own easily.
But for the sake of being able to generate all bindings via this tool, this should be added.

**Comment by EP-u-NW** [comment]
Hm I see your point there.

So reading your `input`, the first thing I noticed is the `className`. Since dart:ffi doesn't support binding against C++ code, I guess this has nothing to do with an actual C++ class, but is more of a generation directive where to place the constant (since you dont want a bunch of top-level constants in your generated library)?

My second thought was, that this needs to be discuessed a bit more. You may notice that everything generated with this tool actually binds against something (structs, globals and functions), but constants on the other hand wouldn't.

If you think this is an important feature, you could implement it and open a PR. A good starting point is the `Element` class (as it already has a name and a documentation property, only a type and a value property is missing), or the `Global` class (which has name, documentation and type; you would just need to to change the `generateSource` a bit). Then, something like this could do:
```
class Constant extends Element {
  final String type;
  final String value;
  const Constant(
      {@required String name, @required this.type, @required this.value, String documentation})
      : super(name: name, documentation: documentation);

  @override
  void generateSource(DartSourceWriter w, Library library) {
    w.write('\n');
    if (documentation != null) {
      w.write('/// ');
      w.writeAll(documentation.split('\n'), '\n/// ');
      w.write('\n');
    }
    w.write(
        'const $type $name = $value;\n');
  }
}
```
(The above code should actually work, but I don't have time for enough testing atm)


I personally dislike the idea of a `className` poperty since it would be inconsistent: you can't group fields and globals into classes, so why should constant be groupable? Instead, one could consider creating a new library for all things you want to group (e.g. like [here](https://pub.dev/documentation/opus_dart/latest/) and [here](https://github.com/EPNW/opus_dart/blob/master/tool/gen.dart), where a new library is used for each c group name).

**Comment by mannprerak2** [comment]
The example I provided was just a quick whip-up.
The point is to be able to put constants which are declared using #define directive in C, as part of the bindings itself.

I can surely work on this and create a PR.

1. We could use wrapperClassName instead of className or you could suggest some other name
2. Wrapping constants with a class is optional,
We could leave this decision to the user, if user provides a wrapperClassName it's gonna be wrapped with a class as in my example, otherwise they will be global constants.

OR

Another way would be having a Constant and a GroupedConstants.
As the name suggests GroupedConstants will take array of constants and wrap them up in a class as well.

I like the latter approach more.

**Comment by mannprerak2** [comment]
@EPNW can you review my PR, please suggest any changes as you feel so
